import re

with open('ui-utils.js', 'r') as f:
    content = f.read()

# Fix syntax error in syncTutorialButtonsUI generated by the previous patch
content = re.sub(
    r'syncTutorialButtonsUI\(\) \{\} else \{\s*UIUtils\.unlockAllTaskButtons\(\);\s*\}\s*\},',
    'syncTutorialButtonsUI() {},\n',
    content,
    flags=re.DOTALL
)

with open('ui-utils.js', 'w') as f:
    f.write(content)
